# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2ebed1a724e0a921edcf06b182e527609dd9409e61f58bf22de1963772a3d3cd761986942ef7d8fc78ed75dbf885528a584336dc83a440e066378bafc3faadbd

test:
  secret_key_base: e764b223fcea18411cc9ddf3a226b37a32e166a7fef23e8327d7b190de2347c9306238f8c6f59c68769ea733c3738c429a5f457e7f0a929a241fc984a45fa709

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
